baseURL = 'http://til.vramana.com/'
languageCode = 'en-us'
title = 'Ramana: TIL'
theme = 'smigle'

[[main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 3

[[main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 4

[[main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 5


[params]
abbrDateFmt = "Jan 2"
author = "Ramana Venkata"
subtitle = "Things I've learned"
brandIconFile = ""
dateFmt = "2006-01-02"

# Options for overriding theme or page defaults
#customStylesheets = ["css/custom.css"]
#readingSpeed = 600
#readingSpeedMin = 25
#readingSpeedMax = 175

[[params.social]]
name = "GitHub"
url = "https://github.com/vramana"

[[params.social]]
name = "Personal Website"
url = "https://blog.vramana.com"

[[params.social]]
name = "Twitter"
url = "https://twitter.com/_vramana"

[[params.social]]
name = "Mastodon"
url = "https://mastodon.social/@vramana"

